apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.bankapp.serviceName }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: {{ .Values.bankapp.name }}
